#!/bin/bash
cd /home/tim/projects/polybee
./run -c ./config-files/evolve-4-entrance-1o-hive-positions.cfg --evolve false --visualise true --tunnel-entrance 305.3,405.3:1 --tunnel-entrance 148.4,248.4:2 --tunnel-entrance 153.6,253.6:0 --tunnel-entrance 268.4,368.4:3 --hive 292.8,75.6:4 --num-iterations 2000
