#!/bin/bash
cd /home/tim/projects/polybee
./run -c ./config-files/evolve-4-entrance-1o-hive-positions.cfg --evolve false --visualise true --tunnel-entrance 217.8,317.8:2 --tunnel-entrance 286.6,386.6:3 --tunnel-entrance 273.3,373.3:1 --tunnel-entrance 178.0,278.0:0 --hive 630.9,55.1:3 --num-iterations 2000
