#!/bin/bash
cd /home/tim/projects/polybee
./run -c ./config-files/evolve-4-entrance-1o-hive-positions.cfg --evolve false --visualise true --tunnel-entrance 217.5,317.5:2 --tunnel-entrance 142.6,242.6:1 --tunnel-entrance 147.6,247.6:0 --tunnel-entrance 227.6,327.6:3 --hive 432.4,783.2:0 --num-iterations 2000
