#!/bin/bash
cd /home/tim/projects/polybee
./run-release -c config-files/evolve-entrance-positions-4-rows-with-energetics-2.cfg --num-bees 50 --rng-seed 0 --evolve-objective 1 --min-visit-count-success 3 --max-visit-count-success 1000 --evolve 0 --visualise 1 --tunnel-entrance=151.8,251.8:1 --tunnel-entrance=247.0,347.0:2 --tunnel-entrance=94.2,194.2:0 --tunnel-entrance=297.2,397.2:3
