#!/bin/bash
cd /home/tim/projects/polybee
./run -c ./config-files/evolve-4-entrance-1o-hive-positions.cfg --evolve false --visualise true --tunnel-entrance 277.5,377.5:1 --tunnel-entrance 157.5,257.5:2 --tunnel-entrance 191.0,291.0:0 --tunnel-entrance 300.6,400.6:3 --hive 482.9,40.7:0 --num-iterations 2000
